name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允許手動觸發

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r document-2form/requirements.txt
        pip install Pillow
    
    - name: Create icon
      run: |
        cd document-2form
        python create_icon.py || echo "Icon creation failed, using default"
    
    - name: Build executable
      run: |
        cd document-2form
        pyinstaller --onefile --windowed --name "WordFormFiller" --icon=icon.ico --add-data "requirements.txt;." --hidden-import "docx" --hidden-import "docx2txt" --hidden-import "tkinter" --hidden-import "tkinter.ttk" --hidden-import "tkinter.filedialog" --hidden-import "tkinter.messagebox" word_form_filler.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: WordFormFiller.exe
        path: document-2form/dist/WordFormFiller.exe
